//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rtc

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// DeleteLayout invokes the rtc.DeleteLayout API synchronously
// api document: https://help.aliyun.com/api/rtc/deletelayout.html
func (client *Client) DeleteLayout(request *DeleteLayoutRequest) (response *DeleteLayoutResponse, err error) {
	response = CreateDeleteLayoutResponse()
	err = client.DoAction(request, response)
	return
}

// DeleteLayoutWithChan invokes the rtc.DeleteLayout API asynchronously
// api document: https://help.aliyun.com/api/rtc/deletelayout.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteLayoutWithChan(request *DeleteLayoutRequest) (<-chan *DeleteLayoutResponse, <-chan error) {
	responseChan := make(chan *DeleteLayoutResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.DeleteLayout(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// DeleteLayoutWithCallback invokes the rtc.DeleteLayout API asynchronously
// api document: https://help.aliyun.com/api/rtc/deletelayout.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) DeleteLayoutWithCallback(request *DeleteLayoutRequest, callback func(response *DeleteLayoutResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *DeleteLayoutResponse
		var err error
		defer close(result)
		response, err = client.DeleteLayout(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// DeleteLayoutRequest is the request struct for api DeleteLayout
type DeleteLayoutRequest struct {
	*requests.RpcRequest
	OwnerId  requests.Integer `position:"Query" name:"OwnerId"`
	AppId    string           `position:"Query" name:"AppId"`
	LayoutId requests.Integer `position:"Query" name:"LayoutId"`
}

// DeleteLayoutResponse is the response struct for api DeleteLayout
type DeleteLayoutResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateDeleteLayoutRequest creates a request to invoke DeleteLayout API
func CreateDeleteLayoutRequest() (request *DeleteLayoutRequest) {
	request = &DeleteLayoutRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("rtc", "2018-01-11", "DeleteLayout", "rtc", "openAPI")
	return
}

// CreateDeleteLayoutResponse creates a response to parse from DeleteLayout response
func CreateDeleteLayoutResponse() (response *DeleteLayoutResponse) {
	response = &DeleteLayoutResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
