//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rtc

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetLayoutInfo invokes the rtc.GetLayoutInfo API synchronously
// api document: https://help.aliyun.com/api/rtc/getlayoutinfo.html
func (client *Client) GetLayoutInfo(request *GetLayoutInfoRequest) (response *GetLayoutInfoResponse, err error) {
	response = CreateGetLayoutInfoResponse()
	err = client.DoAction(request, response)
	return
}

// GetLayoutInfoWithChan invokes the rtc.GetLayoutInfo API asynchronously
// api document: https://help.aliyun.com/api/rtc/getlayoutinfo.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetLayoutInfoWithChan(request *GetLayoutInfoRequest) (<-chan *GetLayoutInfoResponse, <-chan error) {
	responseChan := make(chan *GetLayoutInfoResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.GetLayoutInfo(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// GetLayoutInfoWithCallback invokes the rtc.GetLayoutInfo API asynchronously
// api document: https://help.aliyun.com/api/rtc/getlayoutinfo.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetLayoutInfoWithCallback(request *GetLayoutInfoRequest, callback func(response *GetLayoutInfoResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *GetLayoutInfoResponse
		var err error
		defer close(result)
		response, err = client.GetLayoutInfo(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// GetLayoutInfoRequest is the request struct for api GetLayoutInfo
type GetLayoutInfoRequest struct {
	*requests.RpcRequest
	OwnerId  requests.Integer `position:"Query" name:"OwnerId"`
	AppId    string           `position:"Query" name:"AppId"`
	LayoutId requests.Integer `position:"Query" name:"LayoutId"`
}

// GetLayoutInfoResponse is the response struct for api GetLayoutInfo
type GetLayoutInfoResponse struct {
	*responses.BaseResponse
	RequestId string                  `json:"RequestId" xml:"RequestId"`
	UserPanes GetLayoutInfoUserPanes0 `json:"UserPanes" xml:"UserPanes"`
}

type GetLayoutInfoUserPanes0 struct {
	UserPanes []GetLayoutInfoUserPanes1 `json:"UserPanes" xml:"UserPanes"`
}

type GetLayoutInfoUserPanes1 struct {
	PaneId     int    `json:"PaneId" xml:"PaneId"`
	UserId     string `json:"UserId" xml:"UserId"`
	SourceType string `json:"SourceType" xml:"SourceType"`
}

// CreateGetLayoutInfoRequest creates a request to invoke GetLayoutInfo API
func CreateGetLayoutInfoRequest() (request *GetLayoutInfoRequest) {
	request = &GetLayoutInfoRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("rtc", "2018-01-11", "GetLayoutInfo", "rtc", "openAPI")
	return
}

// CreateGetLayoutInfoResponse creates a response to parse from GetLayoutInfo response
func CreateGetLayoutInfoResponse() (response *GetLayoutInfoResponse) {
	response = &GetLayoutInfoResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
