//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package rtc

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// GetAllLayoutId invokes the rtc.GetAllLayoutId API synchronously
// api document: https://help.aliyun.com/api/rtc/getalllayoutid.html
func (client *Client) GetAllLayoutId(request *GetAllLayoutIdRequest) (response *GetAllLayoutIdResponse, err error) {
	response = CreateGetAllLayoutIdResponse()
	err = client.DoAction(request, response)
	return
}

// GetAllLayoutIdWithChan invokes the rtc.GetAllLayoutId API asynchronously
// api document: https://help.aliyun.com/api/rtc/getalllayoutid.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetAllLayoutIdWithChan(request *GetAllLayoutIdRequest) (<-chan *GetAllLayoutIdResponse, <-chan error) {
	responseChan := make(chan *GetAllLayoutIdResponse, 1)
	errChan := make(chan error, 1)
	err := client.AddAsyncTask(func() {
		defer close(responseChan)
		defer close(errChan)
		response, err := client.GetAllLayoutId(request)
		if err != nil {
			errChan <- err
		} else {
			responseChan <- response
		}
	})
	if err != nil {
		errChan <- err
		close(responseChan)
		close(errChan)
	}
	return responseChan, errChan
}

// GetAllLayoutIdWithCallback invokes the rtc.GetAllLayoutId API asynchronously
// api document: https://help.aliyun.com/api/rtc/getalllayoutid.html
// asynchronous document: https://help.aliyun.com/document_detail/66220.html
func (client *Client) GetAllLayoutIdWithCallback(request *GetAllLayoutIdRequest, callback func(response *GetAllLayoutIdResponse, err error)) <-chan int {
	result := make(chan int, 1)
	err := client.AddAsyncTask(func() {
		var response *GetAllLayoutIdResponse
		var err error
		defer close(result)
		response, err = client.GetAllLayoutId(request)
		callback(response, err)
		result <- 1
	})
	if err != nil {
		defer close(result)
		callback(nil, err)
		result <- 0
	}
	return result
}

// GetAllLayoutIdRequest is the request struct for api GetAllLayoutId
type GetAllLayoutIdRequest struct {
	*requests.RpcRequest
	OwnerId requests.Integer `position:"Query" name:"OwnerId"`
	AppId   string           `position:"Query" name:"AppId"`
}

// GetAllLayoutIdResponse is the response struct for api GetAllLayoutId
type GetAllLayoutIdResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateGetAllLayoutIdRequest creates a request to invoke GetAllLayoutId API
func CreateGetAllLayoutIdRequest() (request *GetAllLayoutIdRequest) {
	request = &GetAllLayoutIdRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("rtc", "2018-01-11", "GetAllLayoutId", "rtc", "openAPI")
	return
}

// CreateGetAllLayoutIdResponse creates a response to parse from GetAllLayoutId response
func CreateGetAllLayoutIdResponse() (response *GetAllLayoutIdResponse) {
	response = &GetAllLayoutIdResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}
